name: eleven_labs
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.7.0
dependencies:

dev_dependencies:
