name: eleven_labs_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.7.0
dependencies:
  openapi_generator_annotations: ^6.1.0
dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  openapi_generator: ^6.1.0
  test: ^1.24.0
scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs