name: eleven_labs_generator
description: Swagger Chppper Json Serializable Generated Code for Eleven Labs API
version: 1.0.0
repository: https://github.com/ArcaneArts/eleven_labs
environment:
  sdk: ^3.7.0
dependencies:
  chopper: ^8.1.0
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.15
  chopper_generator: ^8.1.0
  json_serializable: ^6.9.5
  swagger_dart_code_generator: ^3.0.1
scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs